# Generated by Django 4.1.10 on 2023-11-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_cart_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=100, null=True)),
                ('used', models.BooleanField(default=False)),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
    ]
