# Generated by Django 4.1.10 on 2023-11-21 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='promocode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.promocode'),
        ),
    ]
