# Generated by Django 4.1.10 on 2023-12-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products_images/default.jpg', upload_to='products_images'),
        ),
    ]
