# Generated by Django 4.1.10 on 2023-12-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products_images/default.jpg', upload_to='products_images'),
        ),
    ]
