# Generated by Django 3.2.23 on 2023-12-04 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
