# Generated by Django 3.2.23 on 2023-12-04 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
    ]
