# Generated by Django 3.2.23 on 2023-12-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20231204_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image1',
        ),
    ]
