# Generated by Django 3.2.23 on 2023-12-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_remove_product_product_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
